# Generated by Django 5.1.3 on 2024-11-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoResidencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FonteEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sustentavel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_tarifa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fonteenergia')),
            ],
        ),
    ]
