# Generated by Django 5.1.3 on 2024-11-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_habitat_consumo_kwh_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='tarifa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.tarifaenergia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitat',
            name='fonte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.fonteenergia'),
            preserve_default=False,
        ),
    ]
