# Generated by Django 5.1.3 on 2024-11-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumoResidencial',
            new_name='Habitat',
        ),
        migrations.AddField(
            model_name='fonteenergia',
            name='url_api',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
