# Generated by Django 5.1.3 on 2024-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_consumoresidencial_habitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonteenergia',
            name='url_api',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
