# Generated by Django 5.1.3 on 2024-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fonteenergia_url_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='nome',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
