# Generated by Django 5.1.3 on 2024-11-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consumo_tarifa_habitat_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='fonte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fonteenergia'),
        ),
    ]
