# Generated by Django 5.1.3 on 2024-11-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_habitat_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habitat'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifaenergia'),
        ),
    ]
