version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  django:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-worker:
    build:
      context: ./backend
    command: celery -A gerenciador.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - django
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build:
      context: ./backend
    command: celery -A gerenciador.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - django
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  react:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:5173'
    depends_on:
      - django

